apiVersion: v1
kind: Namespace
metadata:
  name: egos
---
apiVersion: v1
kind: Secret
metadata:
  name: egos-secrets
  namespace: egos
type: Opaque
stringData:
  JWT_SECRETO: "estilo_y_moda_secret_key_2024"
  POSTGRES_AUTH_URL: "postgresql://neondb_owner:npg_8xkCIyHBo3Mn@ep-misty-cell-af9o0x82-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require"
  POSTGRES_TRANSACTION_URL: "postgresql://neondb_owner:npg_8xkCIyHBo3Mn@ep-misty-cell-af9o0x82-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require"
  POSTGRES_MARKETING_URL: "postgresql://neondb_owner:npg_V6NekxIfwP4E@ep-nameless-dust-ae9ihznv-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require"
  POSTGRES_CREDIT_URL: "postgresql://neondb_owner:npg_IykA6tTPxhE3@ep-tiny-butterfly-adf8yext-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"
  POSTGRES_FACTURACION_URL: "postgresql://neondb_owner:npg_8xkCIyHBo3Mn@ep-misty-cell-af9o0x82-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require"
  MONGODB_CATALOG_URI: "mongodb+srv://Vercel-Admin-Productos:RxoNPvRKANmP3pf5@productos.cwnnwsy.mongodb.net/?retryWrites=true&w=majority"
  MONGODB_SOCIAL_URI: "mongodb+srv://Vercel-Admin-socialservice:fA5shIvwxTGbAt1P@socialservice.78vidp7.mongodb.net/?retryWrites=true&w=majority"
  MONGODB_AI_URI: "mongodb+srv://Vercel-Admin-serviceia:JQZMRqti5uyeqluB@serviceia.pi2owta.mongodb.net/?retryWrites=true&w=majority"
  AI_GATEWAY_API_KEY: "sk-6ffa7be4bba74fb3a1caf1e14d350f90"
