apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: egos-backend-config
  namespace: egos
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 3000
    type: HTTP
    requestPath: /salud
  connectionDraining:
    drainingTimeoutSec: 60
  customRequestHeaders:
    headers:
    - "X-Client-Proto: {client_protocol}"
