apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: egos-frontend-config
  namespace: egos
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  quicOverride: DISABLE
