#!/bin/bash

echo "🔄 ACTUALIZANDO BASE DE DATOS A IDs PERSONALIZADOS..."
echo ""
echo "⚠️  IMPORTANTE: Este script modificará las columnas de UUID a VARCHAR(20)"
echo "   Solo ejecutar en base de datos de desarrollo o nueva"
echo ""
echo "📋 SQL a ejecutar:"
echo "   - ALTER TABLE carrito ALTER COLUMN id TYPE VARCHAR(20)"
echo "   - ALTER TABLE pedido ALTER COLUMN id TYPE VARCHAR(20)"
echo "   - ALTER TABLE pago ALTER COLUMN id TYPE VARCHAR(20)"
echo "   - ALTER TABLE pedido_producto ALTER COLUMN id_pedido TYPE VARCHAR(20)"
echo "   - ALTER TABLE carrito_producto ALTER COLUMN id_carrito TYPE VARCHAR(20)"
echo "   - ALTER TABLE pedido_historial ALTER COLUMN id_pedido TYPE VARCHAR(20)"
echo ""
echo "✅ DESPUÉS DE EJECUTAR:"
echo "   - Reinicia Transaction Service"
echo "   - Los nuevos pedidos usarán formato: EM26010200001"
echo "   - Los nuevos carritos usarán formato: CA26010200001"
echo "   - Los nuevos pagos usarán formato: PG26010200001"
echo ""
echo "🔗 Conexión: postgresql://neondb_owner:***@ep-broad-dew-aeujycvn-pooler.c-2.us-east-2.aws.neon.tech/neondb"
echo ""
echo "📝 Para ejecutar manualmente, conecta a PostgreSQL y ejecuta:"
echo "   psql 'postgresql://neondb_owner:npg_2gVs9CfQRuHn@ep-broad-dew-aeujycvn-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require'"
echo ""
echo "   Luego ejecuta cada ALTER TABLE del archivo:"
echo "   /home/jose/E-comerce/backend/services/transaction-service/sql/actualizar-ids-personalizados.sql"
