FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 3008

CMD ["sh", "-c", "cd /app/src && uvicorn main:app --host 0.0.0.0 --port 3008"]
